## handling missing values
- `df,insull()` - to detect missing vals(`isna()` is the same thing)
- `df,fillna()` - to fill missing vals(imputation)
- `df.dropna()` - to remove missing vals
- `df.replce()` - to replace specific vals(imputation)

In [1]:
import numpy as np
import pandas as pd

In [2]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]



df = pd.DataFrame(employee_list, columns=['name', 'age', 'weight', 'salary'])

In [9]:
rows, cols = df.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 14
Cols: 4

In [11]:
df.head()

      name   age  weight     salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [13]:
df.isnull().sum()

name      1
age       3
weight    1
salary    2
dtype: int64

In [ ]:
dropped_df = df.dropna()
# when dropping na, you remove the entire row

print(dropped_df)

        name   age  weight     salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [18]:
filled_df = df.fillna('None')



print(filled_df)

        name   age weight     salary
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0   None  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0       None
9       None  42.0   85.0       None
10     Jenny  None  100.0    25632.0
11      Kenn  None  110.0    25632.0
12       Aly  None   90.0    25582.0
13      John  41.0   85.0  1528000.0

In [21]:
filled_df.isnull().sum()

name      0
age       0
weight    0
salary    0
dtype: int64

In [24]:
sp_col = df[['weight', 'age']].fillna('Pending')

sp_col

     weight      age
0      75.0     36.0
1      74.0     38.0
2      70.0     31.0
3      80.0     34.0
4     100.0     40.0
5   Pending     40.0
6      72.0     33.0
7      85.0     42.0
8      85.0     42.0
9      85.0     42.0
10    100.0  Pending
11    110.0  Pending
12     90.0  Pending
13     85.0     41.0

In [27]:
fd2 = df.fillna(value={'weight': 'pending', 'age': 'unknown', 'Salary': '0.0', 'Name': 'Verification Pending'})

fd2

        name      age   weight     salary
0      James     36.0     75.0  5428000.0
1    Villers     38.0     74.0  3428000.0
2      VKole     31.0     70.0  8428000.0
3      Smith     34.0     80.0  4428000.0
4      Gayle     40.0    100.0  4528000.0
5       Adam     40.0  pending  4528000.0
6     Rooter     33.0     72.0  7028000.0
7   Peterson     42.0     85.0  2528000.0
8      lynda     42.0     85.0        NaN
9        NaN     42.0     85.0        NaN
10     Jenny  unknown    100.0    25632.0
11      Kenn  unknown    110.0    25632.0
12       Aly  unknown     90.0    25582.0
13      John     41.0     85.0  1528000.0

In [29]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }


tech = pd.DataFrame(technologies)

In [31]:
rows, cols = tech.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 7
Cols: 4

In [50]:
tech.isnull().sum()

Courses     0
Fee         2
Duration    2
Discount    3
dtype: int64

In [51]:
tech2 = tech.replace(np.nan, '')

tech2

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [43]:
tech3 = tech.replace({'Courses': np.nan, 'Fee': np.nan}, 'NAMI')

tech3

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1    NAMI  25000.0   40days       NaN
2  Hadoop     NAMI   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5    NAMI     NAMI   50days    2100.0
6    Java  22000.0   55days       NaN

In [47]:
tech.fillna('')

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [49]:
emp_fd = pd.read_csv('pandasBasic\data\employee.csv')

emp_fd

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12424\4035642232.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  emp_fd = pd.read_csv('pandasBasic\data\employee.csv')

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [53]:
emp_fd.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [54]:
emp_fd = emp_fd.fillna(value={'Name': 'V.pending', 'Age': 'Unknown', 'Weight': 'Unknown', 'Salary': 0.0})

emp_fd

         Name      Age   Weight     Salary
0       James     36.0     75.0  5428000.0
1     Villers     38.0     74.0  3428000.0
2       VKole     31.0     70.0  8428000.0
3       Smith     34.0     80.0  4428000.0
4       Gayle     40.0    100.0  4528000.0
5        Adam     40.0  Unknown  4528000.0
6      Rooter     33.0     72.0  7028000.0
7    Peterson     42.0     85.0  2528000.0
8       lynda     42.0     85.0        0.0
9   V.pending     42.0     85.0        0.0
10      Jenny  Unknown    100.0    25632.0
11       Kenn  Unknown    110.0    25632.0
12        Aly  Unknown     90.0    25582.0
13       John     41.0     85.0  1528000.0
14        Ali     26.0     69.0        0.0