# Pandas Basic

## pandas languages:
- numpy - numerical data and mathmetical operations
- matplotlib - data visulation

In [340]:
import numpy as np 
import pandas as pd

In [341]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

## pandas datastructures
- series - a single demisional datastructure. similar to a list
    - homogeneous (of the same dt)
- dataframe - multidimensional table
    - heterogenous

In [342]:
ser1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [343]:
d ={
    "b": 1,
    "a": 0,
    "c": 2,
    "d": 100
}

ser2 = pd.Series(d)

In [344]:
d1 = {
    "a": 0.0,
    "b": 1.0,
    "c": 2.0
}

ser3 = pd.Series(d1)

print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [345]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

ser4 = pd.Series(calories)

print(ser4)

day1     700
day2    2500
day3    1200
dtype: int64

In [346]:
ser5 = pd.Series(5.0, index=['a', 'b', 'c'])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

## data frame:
- indexes (each number)
- columns (each variables)

In [347]:
fruitData = {
    'apple_sales': [3,2,0,2,9,4,7,2],
    'orange_sales': [0,3,2,7,7,8,3,0]
}

# idx = [2000, 2001, 2002, 2003, 2005, 2006, 2007, 2008]
idx = pd.RangeIndex(2000, 2008)

purchases = pd.DataFrame(fruitData, index=[idx])

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [348]:
rows, cols = purchases.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [349]:
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [350]:
purchases.tail()

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

## Importing files with pandas
- `.read_csv()`
- `.read_excel`

In [351]:
employee_df = pd.read_csv('pandasBasic\data\employee.csv')

employee_df.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\3981359950.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  employee_df = pd.read_csv('pandasBasic\data\employee.csv')

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [352]:
rows, cols = employee_df.shape
print('Rows', rows)
print('Cols:', cols)

Rows 15
Cols: 4

In [353]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [354]:
carsDf = pd.read_json('pandasBasic\data\cars.json')

carsDf.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\4159799006.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  carsDf = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [355]:
rows, cols = carsDf.shape
print('Rows', rows)
print('Cols:', cols)

Rows 161
Cols: 11

In [356]:
carsDf.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

## EDA - the first look (step 1 of data prepping)
- data profiling
    - structure(shape)
    - qaulity (missing vals, dups, unique vals)
    - content(data types, dispersion, measures central tendency)

- profiling tech
    - data type and format validation
    - statiscal summaries(descriptive stats, values counts, frequncy checks)
    - uniquness and cardinality
    - pattern recog
    - cross0validation

In [357]:
#getting a brief overview of descriptive statistics(quantitave data)
carsDf.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [358]:
carsDf['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [359]:
carsDf['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [360]:
carsDf.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [361]:
carsDf.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [362]:
carsDf.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [363]:
# .at method to grab spec vals from ds using label
carsDf.at[159, 'MPG']

np.float64(36.0)

In [364]:
# .at method to grab spec vals from ds using the index number
carsDf.iat[159, 1]

np.float64(36.0)

In [365]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

studentDf = pd.DataFrame(student_dict, index=student_dict['Name'])

In [366]:
studentDf.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [367]:
listIdx = studentDf.columns
print('Column names', listIdx)

Column names Index(['Name', 'Age', 'Marks'], dtype='str')

In [368]:
label = studentDf.columns[0]
print(label)

Name

In [369]:
labels_aslist = studentDf.columns.to_list()
print(labels_aslist)

['Name', 'Age', 'Marks']

## EDA w/ csv

In [370]:
e_df = pd.read_csv('pandasBasic\data\employee.csv')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\384986178.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df = pd.read_csv('pandasBasic\data\employee.csv')

In [371]:
e_df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [372]:
e_df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

In [373]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [374]:
rows, cols = e_df.shape
print('Rows', rows)
print('Cols', cols)

Rows 15
Cols 4

In [375]:
e_df2 = pd.read_csv('pandasBasic\data\employee.csv', skiprows=5, header=None)
e_df2

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\2990258197.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df2 = pd.read_csv('pandasBasic\data\employee.csv', skiprows=5, header=None)

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [376]:
e_df3 = pd.read_csv('pandasBasic\data\employee.csv', usecols=[0, 3])
e_df3

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\2727455903.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df3 = pd.read_csv('pandasBasic\data\employee.csv', usecols=[0, 3])

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

## selecting cols

In [377]:
df_cars = pd.read_json('pandasBasic\data\cars.json')
df_cars.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\890329996.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df_cars = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [378]:
df_cars.columns[0]

'Car'

In [379]:
df_cars.columns[[0, 1, 9]]

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [380]:
# this would be called a series using a label
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [381]:
# accessing a series using a index number
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [382]:
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [383]:
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

## frequency analysis - value counts

In [384]:
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [385]:
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}


sales_df = pd.DataFrame(sales_data)

freq = sales_df['Brand'].value_counts()

freq_prod = freq[freq > 1].index[0]

print(freq)
print(f'this item appears more than once {freq_prod}')

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
this item appears more than once Samsung

In [386]:
data = {'score': [85, 92, 88, 75, None, 90, None, 85]}

scoreDf = pd.DataFrame(data)

In [387]:
scoreCounts = scoreDf.value_counts(dropna=False)
print('score', scoreCounts)

score score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

## Converting pandas columns to list

In [388]:
c_df = pd.read_json('pandasBasic\data\cars.json')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\2218313420.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  c_df = pd.read_json('pandasBasic\data\cars.json')

In [389]:
c_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

### converting pandas col to list using .to_list

In [390]:
col_list = c_df['Car'].values.tolist()
print('Carlist', col_list)

Carlist ['Chevrolet Vega', 'Chevrolet Vega (sw)', 'Chevrolet Vega 2300', 'Chevrolet Woody', 'Chevrolete Chevelle Malibu', 'Chevy C20', 'Chevy S-10', 'Chrysler Cordoba', 'Chrysler Lebaron Medallion', 'Chrysler Lebaron Salon', 'Chrysler Lebaron Town @ Country (sw)', 'Chrysler New Yorker Brougham', 'Chrysler Newport Royal', 'Citroen DS-21 Pallas', 'Datsun 1200', 'Datsun 200SX', 'Datsun 200-SX', 'Datsun 210', 'Datsun 210', 'Datsun 210 MPG', 'Datsun 280-ZX', 'Datsun 310', 'Datsun 310 GX', 'Datsun 510', 'Datsun 510 (sw)', 'Datsun 510 Hatchback', 'Datsun 610', 'Datsun 710', 'Datsun 710', 'Datsun 810', 'Datsun 810 Maxima', 'Datsun B210', 'Datsun B-210', 'Datsun B210 GX', 'Datsun F-10 Hatchback', 'Datsun PL510', 'Datsun PL510', 'Dodge Aries SE', 'Dodge Aries Wagon (sw)', 'Dodge Aspen', 'Dodge Aspen', 'Dodge Aspen 6', 'Dodge Aspen SE', 'Dodge Challenger SE', 'Dodge Charger 2.2', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt (sw)', 'Dodge Colt Hardtop', 'Dodge Colt Hatchback Custom', 'Dodge Colt m/m', 'Dodge Coronet Brougham', 'Dodge Coronet Custom', 'Dodge Coronet Custom (sw)', 'Dodge D100', 'Dodge D200', 'Dodge Dart Custom', 'Dodge Diplomat', 'Dodge Magnum XE', 'Dodge Monaco (sw)', 'Dodge Monaco Brougham', 'Dodge Omni', 'Dodge Rampage', 'Dodge St. Regis', 'Fiat 124 Sport Coupe', 'Fiat 124 TC', 'Fiat 124B', 'Fiat 128', 'Fiat 128', 'Fiat 131', 'Fiat Strada Custom', 'Fiat x1.9', 'Ford Country', 'Ford Country Squire (sw)', 'Ford Country Squire (sw)', 'Ford Escort 2H', 'Ford Escort 4W', 'Ford F108', 'Ford F250', 'Ford Fairmont', 'Ford Fairmont (auto)', 'Ford Fairmont (man)', 'Ford Fairmont 4', 'Ford Fairmont Futura', 'Ford Fiesta', 'Ford Futura', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino (sw)', 'Ford Gran Torino (sw)', 'Ford Grenada', 'Ford Grenada ghia', 'Ford Grenada gl', 'Ford Grenada l', 'Ford LTD', 'Ford LTD', 'Ford LTD Landau', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Mustang', 'Ford Mustang Boss 302', 'Ford Mustang Cobra', 'Ford Mustang GL', 'Ford Mustang II', 'Ford Mustang II 2+2', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto (sw)', 'Ford Pinto Runabout', 'Ford Ranger', 'Ford Thunderbird', 'Ford Torino', 'Ford Torino (sw)', 'Ford Torino 500', 'Hi 1200D', 'Honda Accord', 'Honda Accord', 'Honda Accord CVCC', 'Honda Accord LX', 'Honda Civic', 'Honda Civic', 'Honda Civic', 'Honda Civic (auto)', 'Honda Civic 1300', 'Honda Civic 1500 gl', 'Honda Civic CVCC', 'Honda Civic CVCC', 'Honda Prelude', 'Mazda 626', 'Mazda 626', 'Mazda GLC', 'Mazda GLC 4', 'Mazda GLC Custom', 'Mazda GLC Custom l', 'Mazda GLC Deluxe', 'Mazda GLC Deluxe', 'Mazda RX2 Coupe', 'Mazda RX3', 'Mazda RX-4', 'Mazda RX-7 GS', 'Mercedes Benz 300d', 'Mercedes-Benz 240d', 'Mercedes-Benz 280s', 'Mercury Capri 2000', 'Mercury Capri v6', 'Mercury Cougar Brougham', 'Mercury Grand Marquis', 'Mercury Lynx l', 'Mercury Marquis']

In [391]:
c_df.Car.tolist()

['Chevrolet Vega',
 'Chevrolet Vega (sw)',
 'Chevrolet Vega 2300',
 'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',
 'Chevy C20',
 'Chevy S-10',
 'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',
 'Chrysler Lebaron Salon',
 'Chrysler Lebaron Town @ Country (sw)',
 'Chrysler New Yorker Brougham',
 'Chrysler Newport Royal',
 'Citroen DS-21 Pallas',
 'Datsun 1200',
 'Datsun 200SX',
 'Datsun 200-SX',
 'Datsun 210',
 'Datsun 210',
 'Datsun 210 MPG',
 'Datsun 280-ZX',
 'Datsun 310',
 'Datsun 310 GX',
 'Datsun 510',
 'Datsun 510 (sw)',
 'Datsun 510 Hatchback',
 'Datsun 610',
 'Datsun 710',
 'Datsun 710',
 'Datsun 810',
 'Datsun 810 Maxima',
 'Datsun B210',
 'Datsun B-210',
 'Datsun B210 GX',
 'Datsun F-10 Hatchback',
 'Datsun PL510',
 'Datsun PL510',
 'Dodge Aries SE',
 'Dodge Aries Wagon (sw)',
 'Dodge Aspen',
 'Dodge Aspen',
 'Dodge Aspen 6',
 'Dodge Aspen SE',
 'Dodge Challenger SE',
 'Dodge Charger 2.2',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt (sw)',
 'Dodge Colt Hardtop',
 'Dodge Colt Hatchback Custom',
 'Dodge Colt m/m',
 'Dodge Coronet Brougham',
 'Dodge Coronet Custom',
 'Dodge Coronet Custom (sw)',
 'Dodge D100',
 'Dodge D200',
 'Dodge Dart Custom',
 'Dodge Diplomat',
 'Dodge Magnum XE',
 'Dodge Monaco (sw)',
 'Dodge Monaco Brougham',
 'Dodge Omni',
 'Dodge Rampage',
 'Dodge St. Regis',
 'Fiat 124 Sport Coupe',
 'Fiat 124 TC',
 'Fiat 124B',
 'Fiat 128',
 'Fiat 128',
 'Fiat 131',
 'Fiat Strada Custom',
 'Fiat x1.9',
 'Ford Country',
 'Ford Country Squire (sw)',
 'Ford Country Squire (sw)',
 'Ford Escort 2H',
 'Ford Escort 4W',
 'Ford F108',
 'Ford F250',
 'Ford Fairmont',
 'Ford Fairmont (auto)',
 'Ford Fairmont (man)',
 'Ford Fairmont 4',
 'Ford Fairmont Futura',
 'Ford Fiesta',
 'Ford Futura',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino (sw)',
 'Ford Gran Torino (sw)',
 'Ford Grenada',
 'Ford Grenada ghia',
 'Ford Grenada gl',
 'Ford Grenada l',
 'Ford LTD',
 'Ford LTD',
 'Ford LTD Landau',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Mustang',
 'Ford Mustang Boss 302',
 'Ford Mustang Cobra',
 'Ford Mustang GL',
 'Ford Mustang II',
 'Ford Mustang II 2+2',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto (sw)',
 'Ford Pinto Runabout',
 'Ford Ranger',
 'Ford Thunderbird',
 'Ford Torino',
 'Ford Torino (sw)',
 'Ford Torino 500',
 'Hi 1200D',
 'Honda Accord',
 'Honda Accord',
 'Honda Accord CVCC',
 'Honda Accord LX',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic (auto)',
 'Honda Civic 1300',
 'Honda Civic 1500 gl',
 'Honda Civic CVCC',
 'Honda Civic CVCC',
 'Honda Prelude',
 'Mazda 626',
 'Mazda 626',
 'Mazda GLC',
 'Mazda GLC 4',
 'Mazda GLC Custom',
 'Mazda GLC Custom l',
 'Mazda GLC Deluxe',
 'Mazda GLC Deluxe',
 'Mazda RX2 Coupe',
 'Mazda RX3',
 'Mazda RX-4',
 'Mazda RX-7 GS',
 'Mercedes Benz 300d',
 'Mercedes-Benz 240d',
 'Mercedes-Benz 280s',
 'Mercury Capri 2000',
 'Mercury Capri v6',
 'Mercury Cougar Brougham',
 'Mercury Grand Marquis',
 'Mercury Lynx l',
 'Mercury Marquis']

In [392]:
col_numpyArr = c_df['Car'].to_numpy()
print(type(col_numpyArr))

<class 'numpy.ndarray'>

In [393]:
c_df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160]

In [394]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

tech_df = pd.DataFrame(tech)

In [396]:
tech_df = tech_df.rename(columns={'Courses': 'Course Name'})
print(tech_df)

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year