# Pandas Basic

## pandas languages:
- numpy - numerical data and mathmetical operations
- matplotlib - data visulation

In [237]:
import numpy as np 
import pandas as pd

In [238]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

## pandas datastructures
- series - a single demisional datastructure. similar to a list
    - homogeneous (of the same dt)
- dataframe - multidimensional table
    - heterogenous

In [239]:
ser1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [240]:
d ={
    "b": 1,
    "a": 0,
    "c": 2,
    "d": 100
}

ser2 = pd.Series(d)

In [241]:
d1 = {
    "a": 0.0,
    "b": 1.0,
    "c": 2.0
}

ser3 = pd.Series(d1)

print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [242]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

ser4 = pd.Series(calories)

print(ser4)

day1     700
day2    2500
day3    1200
dtype: int64

In [243]:
ser5 = pd.Series(5.0, index=['a', 'b', 'c'])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

## data frame:
- indexes (each number)
- columns (each variables)

In [244]:
fruitData = {
    'apple_sales': [3,2,0,2,9,4,7,2],
    'orange_sales': [0,3,2,7,7,8,3,0]
}

# idx = [2000, 2001, 2002, 2003, 2005, 2006, 2007, 2008]
idx = pd.RangeIndex(2000, 2008)

purchases = pd.DataFrame(fruitData, index=[idx])

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [245]:
rows, cols = purchases.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [246]:
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [247]:
purchases.tail()

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

## Importing files with pandas
- `.read_csv()`
- `.read_excel`

In [248]:
employee_df = pd.read_csv('pandasBasic\data\employee.csv')

employee_df.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\3981359950.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  employee_df = pd.read_csv('pandasBasic\data\employee.csv')

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [249]:
rows, cols = employee_df.shape
print('Rows', rows)
print('Cols:', cols)

Rows 15
Cols: 4

In [250]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [251]:
carsDf = pd.read_json('pandasBasic\data\cars.json')

carsDf.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\4159799006.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  carsDf = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [252]:
rows, cols = carsDf.shape
print('Rows', rows)
print('Cols:', cols)

Rows 161
Cols: 11

In [253]:
carsDf.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

## EDA - the first look (step 1 of data prepping)
- data profiling
    - structure(shape)
    - qaulity (missing vals, dups, unique vals)
    - content(data types, dispersion, measures central tendency)

- profiling tech
    - data type and format validation
    - statiscal summaries(descriptive stats, values counts, frequncy checks)
    - uniquness and cardinality
    - pattern recog
    - cross0validation

In [254]:
#getting a brief overview of descriptive statistics(quantitave data)
carsDf.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [255]:
carsDf['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [256]:
carsDf['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [257]:
carsDf.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [258]:
carsDf.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [259]:
carsDf.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [260]:
# .at method to grab spec vals from ds using label
carsDf.at[159, 'MPG']

np.float64(36.0)

In [261]:
# .at method to grab spec vals from ds using the index number
carsDf.iat[159, 1]

np.float64(36.0)

In [262]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

studentDf = pd.DataFrame(student_dict, index=student_dict['Name'])

In [263]:
studentDf.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [264]:
listIdx = studentDf.columns
print('Column names', listIdx)

Column names Index(['Name', 'Age', 'Marks'], dtype='str')

In [265]:
label = studentDf.columns[0]
print(label)

Name

In [266]:
labels_aslist = studentDf.columns.to_list()
print(labels_aslist)

['Name', 'Age', 'Marks']

## EDA w/ csv

In [267]:
e_df = pd.read_csv('pandasBasic\data\employee.csv')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\384986178.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df = pd.read_csv('pandasBasic\data\employee.csv')

In [268]:
e_df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [269]:
e_df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

In [270]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [271]:
rows, cols = e_df.shape
print('Rows', rows)
print('Cols', cols)

Rows 15
Cols 4

In [272]:
e_df2 = pd.read_csv('pandasBasic\data\employee.csv', skiprows=5, header=None)
e_df2

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\2990258197.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df2 = pd.read_csv('pandasBasic\data\employee.csv', skiprows=5, header=None)

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [273]:
e_df3 = pd.read_csv('pandasBasic\data\employee.csv', usecols=[0, 3])
e_df3

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\2727455903.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  e_df3 = pd.read_csv('pandasBasic\data\employee.csv', usecols=[0, 3])

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

## selecting cols

In [274]:
df_cars = pd.read_json('pandasBasic\data\cars.json')
df_cars.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\890329996.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df_cars = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [275]:
df_cars.columns[0]

'Car'

In [276]:
df_cars.columns[[0, 1, 9]]

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [277]:
# this would be called a series using a label
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [278]:
# accessing a series using a index number
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [279]:
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [280]:
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

## frequency analysis - value counts

In [281]:
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [282]:
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}


sales_df = pd.DataFrame(sales_data)

freq = sales_df['Brand'].value_counts()

freq_prod = freq[freq > 1].index[0]

print(freq)
print(f'this item appears more than once {freq_prod}')

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
this item appears more than once Samsung

In [283]:
data = {'score': [85, 92, 88, 75, None, 90, None, 85]}

scoreDf = pd.DataFrame(data)

In [284]:
scoreCounts = scoreDf.value_counts(dropna=False)
print('score', scoreCounts)

score score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

## Converting pandas columns to list

In [285]:
c_df = pd.read_json('pandasBasic\data\cars.json')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\2218313420.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  c_df = pd.read_json('pandasBasic\data\cars.json')

In [286]:
c_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

### converting pandas col to list using .to_list

In [287]:
col_list = c_df['Car'].values.tolist()
print('Carlist', col_list)

Carlist ['Chevrolet Vega', 'Chevrolet Vega (sw)', 'Chevrolet Vega 2300', 'Chevrolet Woody', 'Chevrolete Chevelle Malibu', 'Chevy C20', 'Chevy S-10', 'Chrysler Cordoba', 'Chrysler Lebaron Medallion', 'Chrysler Lebaron Salon', 'Chrysler Lebaron Town @ Country (sw)', 'Chrysler New Yorker Brougham', 'Chrysler Newport Royal', 'Citroen DS-21 Pallas', 'Datsun 1200', 'Datsun 200SX', 'Datsun 200-SX', 'Datsun 210', 'Datsun 210', 'Datsun 210 MPG', 'Datsun 280-ZX', 'Datsun 310', 'Datsun 310 GX', 'Datsun 510', 'Datsun 510 (sw)', 'Datsun 510 Hatchback', 'Datsun 610', 'Datsun 710', 'Datsun 710', 'Datsun 810', 'Datsun 810 Maxima', 'Datsun B210', 'Datsun B-210', 'Datsun B210 GX', 'Datsun F-10 Hatchback', 'Datsun PL510', 'Datsun PL510', 'Dodge Aries SE', 'Dodge Aries Wagon (sw)', 'Dodge Aspen', 'Dodge Aspen', 'Dodge Aspen 6', 'Dodge Aspen SE', 'Dodge Challenger SE', 'Dodge Charger 2.2', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt (sw)', 'Dodge Colt Hardtop', 'Dodge Colt Hatchback Custom', 'Dodge Colt m/m', 'Dodge Coronet Brougham', 'Dodge Coronet Custom', 'Dodge Coronet Custom (sw)', 'Dodge D100', 'Dodge D200', 'Dodge Dart Custom', 'Dodge Diplomat', 'Dodge Magnum XE', 'Dodge Monaco (sw)', 'Dodge Monaco Brougham', 'Dodge Omni', 'Dodge Rampage', 'Dodge St. Regis', 'Fiat 124 Sport Coupe', 'Fiat 124 TC', 'Fiat 124B', 'Fiat 128', 'Fiat 128', 'Fiat 131', 'Fiat Strada Custom', 'Fiat x1.9', 'Ford Country', 'Ford Country Squire (sw)', 'Ford Country Squire (sw)', 'Ford Escort 2H', 'Ford Escort 4W', 'Ford F108', 'Ford F250', 'Ford Fairmont', 'Ford Fairmont (auto)', 'Ford Fairmont (man)', 'Ford Fairmont 4', 'Ford Fairmont Futura', 'Ford Fiesta', 'Ford Futura', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino (sw)', 'Ford Gran Torino (sw)', 'Ford Grenada', 'Ford Grenada ghia', 'Ford Grenada gl', 'Ford Grenada l', 'Ford LTD', 'Ford LTD', 'Ford LTD Landau', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Mustang', 'Ford Mustang Boss 302', 'Ford Mustang Cobra', 'Ford Mustang GL', 'Ford Mustang II', 'Ford Mustang II 2+2', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto (sw)', 'Ford Pinto Runabout', 'Ford Ranger', 'Ford Thunderbird', 'Ford Torino', 'Ford Torino (sw)', 'Ford Torino 500', 'Hi 1200D', 'Honda Accord', 'Honda Accord', 'Honda Accord CVCC', 'Honda Accord LX', 'Honda Civic', 'Honda Civic', 'Honda Civic', 'Honda Civic (auto)', 'Honda Civic 1300', 'Honda Civic 1500 gl', 'Honda Civic CVCC', 'Honda Civic CVCC', 'Honda Prelude', 'Mazda 626', 'Mazda 626', 'Mazda GLC', 'Mazda GLC 4', 'Mazda GLC Custom', 'Mazda GLC Custom l', 'Mazda GLC Deluxe', 'Mazda GLC Deluxe', 'Mazda RX2 Coupe', 'Mazda RX3', 'Mazda RX-4', 'Mazda RX-7 GS', 'Mercedes Benz 300d', 'Mercedes-Benz 240d', 'Mercedes-Benz 280s', 'Mercury Capri 2000', 'Mercury Capri v6', 'Mercury Cougar Brougham', 'Mercury Grand Marquis', 'Mercury Lynx l', 'Mercury Marquis']

In [288]:
c_df.Car.tolist()

['Chevrolet Vega',
 'Chevrolet Vega (sw)',
 'Chevrolet Vega 2300',
 'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',
 'Chevy C20',
 'Chevy S-10',
 'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',
 'Chrysler Lebaron Salon',
 'Chrysler Lebaron Town @ Country (sw)',
 'Chrysler New Yorker Brougham',
 'Chrysler Newport Royal',
 'Citroen DS-21 Pallas',
 'Datsun 1200',
 'Datsun 200SX',
 'Datsun 200-SX',
 'Datsun 210',
 'Datsun 210',
 'Datsun 210 MPG',
 'Datsun 280-ZX',
 'Datsun 310',
 'Datsun 310 GX',
 'Datsun 510',
 'Datsun 510 (sw)',
 'Datsun 510 Hatchback',
 'Datsun 610',
 'Datsun 710',
 'Datsun 710',
 'Datsun 810',
 'Datsun 810 Maxima',
 'Datsun B210',
 'Datsun B-210',
 'Datsun B210 GX',
 'Datsun F-10 Hatchback',
 'Datsun PL510',
 'Datsun PL510',
 'Dodge Aries SE',
 'Dodge Aries Wagon (sw)',
 'Dodge Aspen',
 'Dodge Aspen',
 'Dodge Aspen 6',
 'Dodge Aspen SE',
 'Dodge Challenger SE',
 'Dodge Charger 2.2',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt (sw)',
 'Dodge Colt Hardtop',
 'Dodge Colt Hatchback Custom',
 'Dodge Colt m/m',
 'Dodge Coronet Brougham',
 'Dodge Coronet Custom',
 'Dodge Coronet Custom (sw)',
 'Dodge D100',
 'Dodge D200',
 'Dodge Dart Custom',
 'Dodge Diplomat',
 'Dodge Magnum XE',
 'Dodge Monaco (sw)',
 'Dodge Monaco Brougham',
 'Dodge Omni',
 'Dodge Rampage',
 'Dodge St. Regis',
 'Fiat 124 Sport Coupe',
 'Fiat 124 TC',
 'Fiat 124B',
 'Fiat 128',
 'Fiat 128',
 'Fiat 131',
 'Fiat Strada Custom',
 'Fiat x1.9',
 'Ford Country',
 'Ford Country Squire (sw)',
 'Ford Country Squire (sw)',
 'Ford Escort 2H',
 'Ford Escort 4W',
 'Ford F108',
 'Ford F250',
 'Ford Fairmont',
 'Ford Fairmont (auto)',
 'Ford Fairmont (man)',
 'Ford Fairmont 4',
 'Ford Fairmont Futura',
 'Ford Fiesta',
 'Ford Futura',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino (sw)',
 'Ford Gran Torino (sw)',
 'Ford Grenada',
 'Ford Grenada ghia',
 'Ford Grenada gl',
 'Ford Grenada l',
 'Ford LTD',
 'Ford LTD',
 'Ford LTD Landau',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Mustang',
 'Ford Mustang Boss 302',
 'Ford Mustang Cobra',
 'Ford Mustang GL',
 'Ford Mustang II',
 'Ford Mustang II 2+2',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto (sw)',
 'Ford Pinto Runabout',
 'Ford Ranger',
 'Ford Thunderbird',
 'Ford Torino',
 'Ford Torino (sw)',
 'Ford Torino 500',
 'Hi 1200D',
 'Honda Accord',
 'Honda Accord',
 'Honda Accord CVCC',
 'Honda Accord LX',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic (auto)',
 'Honda Civic 1300',
 'Honda Civic 1500 gl',
 'Honda Civic CVCC',
 'Honda Civic CVCC',
 'Honda Prelude',
 'Mazda 626',
 'Mazda 626',
 'Mazda GLC',
 'Mazda GLC 4',
 'Mazda GLC Custom',
 'Mazda GLC Custom l',
 'Mazda GLC Deluxe',
 'Mazda GLC Deluxe',
 'Mazda RX2 Coupe',
 'Mazda RX3',
 'Mazda RX-4',
 'Mazda RX-7 GS',
 'Mercedes Benz 300d',
 'Mercedes-Benz 240d',
 'Mercedes-Benz 280s',
 'Mercury Capri 2000',
 'Mercury Capri v6',
 'Mercury Cougar Brougham',
 'Mercury Grand Marquis',
 'Mercury Lynx l',
 'Mercury Marquis']

In [289]:
col_numpyArr = c_df['Car'].to_numpy()
print(type(col_numpyArr))

<class 'numpy.ndarray'>

In [290]:
c_df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160]

In [291]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

tech_df = pd.DataFrame(tech)

In [292]:
tech_df = tech_df.rename(columns={'Courses': 'Course Name'})

In [293]:
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year

## Sort using pandas

- `.sort_values()`

In [294]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}



grades_df = pd.DataFrame(data)

grades_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [295]:
grades_df = grades_df.assign(address=['NYC', 'NJ', 'CA', 'PA',])

grades_df.head()

     Name  Height Qualification  Score 1  Score 2 address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [296]:
print(grades_df.sort_values(by='Score 1'))

     Name  Height Qualification  Score 1  Score 2 address
3    Fadi     5.2           Msc       45       30      PA
0    Jane     5.1           Msc       56       50     NYC
2   James     5.1           Msc       77       60      CA
1  Princi     6.2            MA       86       96      NJ

In [297]:
print(grades_df.sort_values(by='Score 1', ascending=False))

     Name  Height Qualification  Score 1  Score 2 address
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
0    Jane     5.1           Msc       56       50     NYC
3    Fadi     5.2           Msc       45       30      PA

In [298]:
carz = pd.read_json('pandasBasic\data\cars.json')

carz.head(15)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_15228\2765365751.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  carz = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS
14,Datsun 1200,35.0,4,72.0,69,1613,18.0,71,Japan,99,TEXAS

In [299]:
print(carz.sort_values(by='quantity', ascending=True))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
123                 Ford Torino  17.0          8         302.0         140
112         Ford Mustang II 2+2  25.5          4         140.0          89
6                    Chevy S-10  31.0          4         119.0          82
7              Chrysler Cordoba  15.5          8         400.0         190
121                 Ford Ranger  28.0          4         120.0          79
..                          ...   ...        ...           ...         ...
128                Honda Accord  36.0          4         107.0          75
134          Honda Civic (auto)  32.0          4          91.0          67
22                Datsun 310 GX  38.0          4          91.0          67
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
110             Ford Mustang GL  27.0          4         140.0          86

     Weight  Acceleration  Model Origin  quantity     city
123    3449          10.5     70     US         5       OH
112    2755          15.8     77     US         5       NJ
6      2720          19.4     82     US         7  NewYork
7      4325          12.2     77     US         7       NJ
121    2625          18.6     82     US         7   DALLAS
..      ...           ...    ...    ...       ...      ...
128    2205          14.5     82  Japan       427       OH
134    1965          15.7     82  Japan       430    TEXAS
22     1995          16.2     82  Japan       431       NJ
8      2585          14.5     82     US       434   DALLAS
110    2790          15.6     82     US       439       OH

[161 rows x 11 columns]

In [300]:
print(carz.sort_values(by=['quantity', 'Car'], ascending=[False, True]))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
110             Ford Mustang GL  27.0          4         140.0          86
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
22                Datsun 310 GX  38.0          4          91.0          67
134          Honda Civic (auto)  32.0          4          91.0          67
128                Honda Accord  36.0          4         107.0          75
..                          ...   ...        ...           ...         ...
121                 Ford Ranger  28.0          4         120.0          79
130             Honda Accord LX  29.5          4          98.0          68
147            Mazda GLC Deluxe  34.1          4          86.0          65
112         Ford Mustang II 2+2  25.5          4         140.0          89
123                 Ford Torino  17.0          8         302.0         140

     Weight  Acceleration  Model Origin  quantity    city
110    2790          15.6     82     US       439      OH
8      2585          14.5     82     US       434  DALLAS
22     1995          16.2     82  Japan       431      NJ
134    1965          15.7     82  Japan       430   TEXAS
128    2205          14.5     82  Japan       427      OH
..      ...           ...    ...    ...       ...     ...
121    2625          18.6     82     US         7  DALLAS
130    2135          16.6     78  Japan         7      NJ
147    1975          15.2     79  Japan         7      NJ
112    2755          15.8     77     US         5      NJ
123    3449          10.5     70     US         5      OH

[161 rows x 11 columns]

## slicing a dataframe with .iloc[] / .loc[]
- `df.loc['row', colName , colName]` - label based indexing
- `df.iloc['row',colNum : colNUm]` - index based location

In [301]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]


e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [302]:
e_df.iloc[:1]

    Name  Age  Weight   Salary
0  James   36      75  5428000

In [303]:
e_df.iloc[:2, :2]

      Name  Age
0    James   36
1  Villers   38

In [304]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}


curry = pd.DataFrame(basketball)

In [305]:
curry.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [306]:
curry.loc[:, ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [307]:
curry.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G

## handling missing values
- `df,insull()` - to detect missing vals(`isna()` is the same thing)
- `df,fillna()` - to fill missing vals(imputation)
- `df.dropna()` - to remove missing vals
- `df.replce()` - to replace specific vals(imputation)

## Pandas date & time
- `pd.to_datetime()` - convert diff data types into datetime obj
- `pd.date_range()` - used to generate a range of date and time 
- `pd.timestamp()` - generate the time expressed as number of seconds since 01/01/70

In [308]:
# generate a range of dates from start to end, freq(defualt)
date_range = pd.date_range(start='04/01/2023', end='05/05/2026', periods=5)

date_range # include print() statement if using python termminal.

DatetimeIndex(['2023-04-01 00:00:00', '2024-01-08 12:00:00',
               '2024-10-17 00:00:00', '2025-07-26 12:00:00',
               '2026-05-05 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [309]:
date_range2 = pd.date_range(start='01/01/2020', end='05/05/2026', freq='QE')

date_range2

DatetimeIndex(['2020-03-31', '2020-06-30', '2020-09-30', '2020-12-31',
               '2021-03-31', '2021-06-30', '2021-09-30', '2021-12-31',
               '2022-03-31', '2022-06-30', '2022-09-30', '2022-12-31',
               '2023-03-31', '2023-06-30', '2023-09-30', '2023-12-31',
               '2024-03-31', '2024-06-30', '2024-09-30', '2024-12-31',
               '2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31'],
              dtype='datetime64[us]', freq='QE-DEC')

In [310]:
date_range3 = pd.date_range(start='01/01/2024', periods=6, tz='Asia/Tokyo')

date_range3

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-01-02 00:00:00+09:00',
               '2024-01-03 00:00:00+09:00', '2024-01-04 00:00:00+09:00',
               '2024-01-05 00:00:00+09:00', '2024-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [311]:
Start_d = '01/01/2023'
num_d =30

date_range = pd.date_range(start=Start_d, periods=num_d, freq='D')

np.random.seed(42)
stock_prices = np.random.normal(loc=100, scale=5, size=num_d).round(2)



stock_d = pd.DataFrame({'Date': date_range, 'Stockprice': stock_prices})

stock_d

         Date  Stockprice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [312]:
import datetime

timestamp = pd.Timestamp('2026-05-06 13:38:00', tz='America/New_York')

print(timestamp)
print(type(timestamp))

dt_ts = datetime.datetime(2026, 5, 5, 13, 38)

print(dt_ts)
print(type(dt_ts))

2026-05-06 13:38:00-04:00
<class 'pandas.Timestamp'>
2026-05-05 13:38:00
<class 'datetime.datetime'>

In [313]:
timestamp.year

2026

In [314]:
timestamp.day

6

In [315]:
timestamp.dayofweek

2

In [316]:
dates = ['2026-05-05', '2024-10-12', '2013-08-19']

dates
print(type(dates))

output = pd.to_datetime(dates)

print(output)

<class 'list'>
DatetimeIndex(['2026-05-05', '2024-10-12', '2013-08-19'], dtype='datetime64[us]', freq=None)

In [317]:
input_l = ['2023-01-01', '2023-05-16', '3/10/2025 143045', '13th of November, 2025']

print(input_l)

output = pd.to_datetime(input_l, format='mixed')

print(output)

['2023-01-01', '2023-05-16', '3/10/2025 143045', '13th of November, 2025']
DatetimeIndex(['2023-01-01 00:00:00', '2023-05-16 00:00:00',
               '2025-03-10 14:30:45', '2025-11-13 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [318]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})

In [319]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [320]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')

df.head()

   patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00

In [321]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed', errors='coerce')

df

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [322]:
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
tesla_df = pd.read_csv(url, parse_dates=['Date'])


tesla_df.head()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [323]:
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['year'] = tesla_df['Date'].dt.year


tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,year
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,29,2010
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,30,2010
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,1,2010
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2,2010
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,6,2010
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,7,8,2010
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,7,9,2010
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,7,12,2010
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,7,13,2010

In [324]:
most_rec = tesla_df['Date'].min()
least_rec = tesla_df['Date'].max()


print(most_rec)
print(least_rec)

2010-06-29 00:00:00
2017-08-08 00:00:00

In [325]:
monthly_sales = tesla_df.groupby(['year', 'Month'])['Volume'].sum().reset_index()


monthly_sales.head(15)

    year  Month    Volume
0   2010      6  35953400
1   2010      7  64575800
2   2010      8  15038200
3   2010      9  18045900
4   2010     10   6547800
5   2010     11  28315100
6   2010     12  36892900
7   2011      1  28420100
8   2011      2  29303500
9   2011      3  32563300
10  2011      4  29894900
11  2011      5  30348800
12  2011      6  39727300
13  2011      7  21102100
14  2011      8  27215700

## filter using loc[] or query()

In [326]:
filt_date = tesla_df.loc[tesla_df['Date'] >= '2010-02-01']

filt_date

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,year
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,29,2010
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,30,2010
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,1,2010
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2,2010
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,6,2010
...,...,...,...,...,...,...,...,...,...,...
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500,8,2,2017
1787,2017-08-03,345.329987,350.000000,343.149994,347.089996,347.089996,13535000,8,3,2017
1788,2017-08-04,347.000000,357.269989,343.299988,356.910004,356.910004,9198400,8,4,2017
1789,2017-08-07,357.350006,359.480011,352.750000,355.170013,355.170013,6276900,8,7,2017
1790,2017-08-08,357.529999,368.579987,357.399994,365.220001,365.220001,7449837,8,8,2017

In [327]:
# filtr_dt = tesla_df.query() # will probably us this over .loc[]